package com.hci.ren.feature.plangeneration

enum class PlanStatus {
    Uploading, Analyzing, IdentifyingTopics, CreatingBlocks, Finalizing, Completed, Failed;

    companion object {
        fun fromWire(value: String) = when (value) {
            "ANALYZING" -> Analyzing
            "IDENTIFYING_TOPICS" -> IdentifyingTopics
            "CREATING_BLOCKS" -> CreatingBlocks
            "FINALIZING" -> Finalizing
            "COMPLETED" -> Completed
            "FAILED" -> Failed
            "CANCELED" -> Failed
            else -> Failed
        }
    }
}

enum class GenerationFailurePhase {
    UploadOrCreate,
    Polling,
    BackendTerminal,
}

const val DEFAULT_PROJECT_NAME = "Study plan"

internal fun requestIdForRetry(
    previousRequestId: String,
    phase: GenerationFailurePhase,
    newId: () -> String,
): String = if (phase == GenerationFailurePhase.BackendTerminal) newId() else previousRequestId

internal fun isRetryableStatusCode(code: Int): Boolean =
    code == 408 || code == 429 || code >= 500

data class StudyTopic(val id: String, val title: String, val order: Int)
enum class TaskPriority { High, Medium, Low }
enum class StudyTaskType(val defaultMinimumMinutes: Int) {
    Concept(20),
    Practice(15),
    Review(10),
    MockTest(30),
    Memorization(10),
    Reading(15),
    Summary(10),
    MistakeReview(10),
    Custom(10),
    // Kept for compatibility with plans generated by older backend prompts.
    Learn(20),
    Quiz(10),
    MockExam(30),
    Skim(5),
}
enum class StudyTaskStatus {
    NotStarted,
    InProgress,
    Completed,
    Skipped,
    Locked,
    Overdue,
    Rescheduled,
    Optional,
    Excluded,
    Unscheduled,
    OverCapacity,
}
enum class TaskDisposition { MustComplete, IfTimeRemains, Postponed }
enum class StudyScopeGoal { PassExam, ReviseOnly, Fundamentals, SkimEverything, SelectedTopics, CompleteEverything }
data class GeneratedStudyBlock(
    val id: String,
    val title: String,
    val order: Int,
    val durationMinutes: Int,
    val instructions: String,
    val topicIds: List<String>,
    val minimumUsefulMinutes: Int = 10,
    val priority: TaskPriority = TaskPriority.Medium,
    val taskType: StudyTaskType = StudyTaskType.Review,
    val priorityReason: String = "Supports the study goal",
    val isSkippable: Boolean = true,
    val disposition: TaskDisposition = TaskDisposition.MustComplete,
    val status: StudyTaskStatus = StudyTaskStatus.NotStarted,
    val scheduledDate: String? = null,
    val dependencies: List<String> = emptyList(),
    val isOptional: Boolean = disposition == TaskDisposition.IfTimeRemains,
    val isExcluded: Boolean = false,
)
data class GeneratedStudyPlan(
    val id: String,
    val topics: List<StudyTopic>,
    val blocks: List<GeneratedStudyBlock>,
    val totalEstimatedMinutes: Int,
    val projectName: String = DEFAULT_PROJECT_NAME,
)

data class PlanGenerationUiState(
    val status: PlanStatus = PlanStatus.Uploading,
    val planId: String? = null,
    val plan: GeneratedStudyPlan? = null,
    val feasibility: FeasibilityResult? = null,
    val originalGoalDoesNotFit: Boolean = false,
    val dailyStudyMinutesOverride: Int? = null,
    val acceptedTightPlan: Boolean = false,
    val changeMessage: String? = null,
    val errorMessage: String? = null,
)

