package com.hci.ren.ui.theme

import androidx.compose.ui.graphics.Color

val RenGreen = Color(0xFF55AA79)
val RenGreenDark = Color(0xFF2F7D55)
val RenGreenContainer = Color(0xFFEAF7EF)
val RenBackground = Color(0xFFFCFCF9)
val RenSurface = Color(0xFFFFFFFF)
val RenSurfaceMuted = Color(0xFFF5F6F3)
val RenBorder = Color(0xFFE5E8E2)
val RenText = Color(0xFF20231F)
val RenTextMuted = Color(0xFF6D736C)
val RenSage = Color(0xFF607A6A)
val RenSageLight = Color(0xFF9DB8A6)
val RenSageContainer = Color(0xFFE4ECE6)
val RenSageContainerDark = Color(0xFF34483B)
val RenTaupe = Color(0xFF796F62)
val RenTaupeLight = Color(0xFFB7AA99)
val RenTaupeContainer = Color(0xFFF0ECE6)
val RenTaupeContainerDark = Color(0xFF4B4339)

internal val RenDarkOnPrimary = Color(0xFF0D321F)
internal val RenDarkOnSecondary = Color(0xFF183426)
internal val RenDarkOnSecondaryContainer = Color(0xFFD8E8DC)
internal val RenDarkOnTertiary = Color(0xFF372F26)
internal val RenDarkOnTertiaryContainer = Color(0xFFF0E2D2)
internal val RenDarkBackground = Color(0xFF000000)
internal val RenDarkOnBackground = Color(0xFFE2E4DF)
internal val RenDarkSurface = Color(0xFF0A0D0A)
internal val RenDarkSurfaceVariant = Color(0xFF111611)
internal val RenDarkOnSurfaceVariant = Color(0xFFC2C8C0)
internal val RenDarkInverseOnSurface = Color(0xFF2D312D)
internal val RenDarkSurfaceBright = Color(0xFF222822)
internal val RenDarkSurfaceContainerLowest = Color(0xFF000000)
internal val RenDarkSurfaceContainer = Color(0xFF0F140F)
internal val RenDarkSurfaceContainerHighest = Color(0xFF1A201A)
internal val RenDarkOutline = Color(0xFF8C938A)
internal val RenDarkOutlineVariant = Color(0xFF283028)

internal val RenLightInverseSurface = Color(0xFF2E312D)
internal val RenLightInverseOnSurface = Color(0xFFF1F2EE)
internal val RenLightSurfaceDim = Color(0xFFDCDDD9)
internal val RenLightSurfaceContainerHigh = Color(0xFFEFF1ED)
internal val RenLightSurfaceContainerHighest = Color(0xFFE8EAE6)
